### ISSUE TITLE
Errors when loading sprites

### ISSUE THREAD

**Issue by SamiAlavi** [watergis/mapbox-gl-legend#8]
The plugin seems to working correctly but is giving these errors when loading sprites. When I comment out `lines 261, 262` in the file `dist/index.js` the errors stop.

![image](https://user-images.githubusercontent.com/32700289/111668126-3e9d3100-8837-11eb-981b-a8ad676621af.png)
![image](https://user-images.githubusercontent.com/32700289/111668420-8c199e00-8837-11eb-9aa5-42bbb69a4f21.png)

**Comment by JinIgarashi** [comment]
@SamiAlavi Thank you for the issue. I haven’t tested sprite url for Mapbox studio in this plugin because I am self hosting sprite.
You may comment out these two lines in order to stop errors, but it is not permanent solution. These lines are necessary to show some symbol icons.

**Comment by JinIgarashi** [comment]
@SamiAlavi I fixed this bug in this [PR](https://github.com/watergis/mapbox-gl-legend/pull/9). Could you check [feature/adopt4mapboxstyleurl](https://github.com/watergis/mapbox-gl-legend/tree/feature/adopt4mapboxstyleurl) branch whether it can work in your environment? If it can work, I will merge and release as new version.

**Comment by SamiAlavi** [comment]
The error is still there. I checked the value of accessToken being used in `dist/index.js` and it was `null`. When I manually set my accessToken, then no errors came. Hence, I think the accessToken will have to be passed in the constructor.

![image](https://user-images.githubusercontent.com/32700289/111788057-782a7680-88e1-11eb-98b0-3d2651c70eff.png)

**Comment by JinIgarashi** [comment]
@SamiAlavi this issue might be the same with mapbox-gl-export. let me think how I can fix it for v2 users.

**Comment by JinIgarashi** [comment]
@SamiAlavi I think the issue was resolved, so I merged and released it as [v1.1.4](https://github.com/watergis/mapbox-gl-legend/releases/tag/v1.1.4) although there is still an issue of accesstoken for your v2 environment.
